### ISSUE TITLE
Надо сделать так, чтобы у проекта всегда была референция

### ISSUE THREAD

**Issue by sintsov** [Golenzovskiy/altrc#10]
_всплыл еще один баг - см. CarPrice, если не сохранил варианты формулировок, как теперь редактировать проект?_

Так как смысл системы именно в том, что у проекта должна быть референция, нужно запретить создавать и редактировать проект без референции.

**Comment by sintsov** [comment]
Если все таки это спорный тезис, имеет смысл написать уточняющий вопрос заказчику.

**Comment by Golenzovskiy** [comment]
@skyeone, имеется 2 варианта решения.
1 - предусмотреть возможность открытия проектов на редактирование без референций
2 - исключить возможность удалять единственную референцию проекта

1 вариант противоречит реализованной в системе концепции - у каждого проекта должна быть как минимум одна референция. Если концепция сохраняется, то реализация 1 варианта бессмысленна, т.к. в таком случае проектов без референций не должно быть в принципе и следует реализовать 2 вариант решения.

Оставляем ли мы существующую концепцию и реализуем 2 вариант, либо меняем концепцию и применяем 1 способ решения?

**Comment by skyeone** [comment]
От Леши: "Без проблем - просто запретите так делать и все - если не заполнил поле референция, то сохранить нельзя - это видимо самый простой вариант"
