### ISSUE TITLE
Имена логотипов

### ISSUE THREAD

**Issue by sintsov** [Golenzovskiy/altrc#18]
с лого у нас есть проблема, что при импорте, что при сохранение. Сейчас если имена логотипов совпадают, то случайно ты можешь перезатереть логотип другого проекта. Нам бы нужно допилить проверку существования файла с таким именем, и если он существует, тогда добавлять ему _increment++.
- [x] Исправить при сохранении
- [ ] <del>Исправить при импорте<del>

**Comment by Golenzovskiy** [comment]
Для истории:
Исправление для импорта решено не делать.
