### ISSUE TITLE
Взаимодействие с полями фильтров

### ISSUE THREAD

**Issue by Golenzovskiy** [Golenzovskiy/altrc#2]
Нужно сделать так, чтобы можно было менять названия самих сущностей в фильтрах, удалять сущности (удалить массив "машиностроение" из присвоенных проектам и из списка, например, но оставить сами проекты)

Другой вопрос, что эти проекты (без присвоенных свойств) должны находиться по какой-то кнопке (может, в каждом фильтре должно быть обязательное поле "Прочие") для ситуаций, когда у проекта не присвоены какие-то свойства (услуга или география, например)

И даже более важно, чтобы можно было значение менять массиву проектов. Ну например, сейчас по ошибке существует в фильтре отрасль со значением "?". Было бы круто взять и убрать все проекты из нее в правильные отрасли, не заходя в каждый проект по отдельности.

**Comment by sintsov** [comment]
В общем я узнал, что в текущей итерации нам еще надо доделать.
1. географию убираем из редактирования и заменяем на редактирование тегов.
2. далее по каждому элементу выводим кол-во проектов с ним связанных, и само название элемента должно быть ссылкой нажав на которую раскрывается список названий проектов.
![image](https://cloud.githubusercontent.com/assets/7813708/18607552/64b60048-7cd8-11e6-82f7-38f234af6930.png)

Это нужно, чтобы редактируя названия справочника ты мог сразу увидеть какие еще проекты это затронет

поскольку это дополнительная задача в рамках первого этапа. если возникнут какие то серьезные трудности сразу писать мне.
