### ISSUE TITLE
Интерфейс для работы со справочниками

### ISSUE THREAD

**Issue by sintsov** [Golenzovskiy/altrc#21]
Суть задачи тут https://github.com/SGolenzovskiy/altrc/issues/2
Что требуется:
- [x] географию убираем из редактирования и заменяем на редактирование тегов
- [x] далее по каждому элементу выводим кол-во проектов с ним связанных, и само название элемента должно быть ссылкой нажав на которую раскрывается список названий проектов.

Вторую часть задачи требуется реализовать только интерфейс! Логика будет реализована в рамках тикета https://github.com/SGolenzovskiy/altrc/issues/2

**Comment by Golenzovskiy** [comment]
Пример выведен на /dictionarys#sectors
