### ISSUE TITLE
Тэги не работают должным образом

### ISSUE THREAD

**Issue by skyeone** [Golenzovskiy/altrc#30]
Пример кейса:

Вбиваем в поисковой строке "ритейл", получаем список проектов в котором есть проект для "Петровича" и набор тэгов: DIY E-commerce  Fashion  Интернет Ритейл Стройматериалы.

В самом проекте указаны все перечисленные тэги. 

Я тыкаю тэг DIY, результаты: проектов нет.

**Comment by sintsov** [comment]
Тестовый кейс воспроизвелся.

@SGolenzovskiy для начала нужно понять почему так происходит, вроде на этапе теста теги работали окей. Обязательно банально проверь может на площадку заказчику, какие то правки не попали.
