### ISSUE TITLE
Интерфейс референций

### ISSUE THREAD

**Issue by skyeone** [Golenzovskiy/altrc#32]
Как сейчас:
![now_1](https://cloud.githubusercontent.com/assets/20903401/19120181/bd9d302c-8b2a-11e6-85fc-52ec257e4641.jpg)

Как должно быть:
![how it should be_1](https://cloud.githubusercontent.com/assets/20903401/19120202/cc5ba9ae-8b2a-11e6-8920-debe3a897559.jpg)
- Красная звездочка - либо отображается, либо нет. Означает наличие отзыва у проекта
- Следующая кнопка - открыть список формулировок (сейчас -тыканьем на красный пунктирный текст)
- Галка - то же, что и ранее - по умолчанию добавить первую референцию (она же=название проекта) в формируемый список референций

**Comment by sintsov** [comment]
@SGolenzovskiy я тебя проконсультирую в личку по каждому элементу

**Comment by sintsov** [comment]
# 

# Красная звездочка - либо отображается, либо нет. Означает наличие отзыва у проекта

Надо добавить некий индикатор (например в виде звездочки), есть ли галочка у проекта или нет,
А чтобы это реализовать мы добавляем еще 1 поле для сущности проект:
- "Есть отзыв"
- отображаем его в редактирование/удаление проекта (фильтрации по этому полю в этом этапе нет) 
- если у проекта установлена эта галка - значит показываем звездочку, если нет, значит нет

**Comment by sintsov** [comment]
# 

# Следующая кнопка - открыть список формулировок (сейчас -тыканьем на красный пунктирный текст)

Сейчас у нас раскрывается список референций нажатием на первую референцию, а нужно по нажатию на кнопку

**Comment by sintsov** [comment]
# 

# Галка - то же, что и ранее - по умолчанию добавить первую референцию (она же=название проекта) в формируемый список референций

Это такая же галка как сейчас в списке референций, нажав на которую основная рефа добавляется в список отобранных референций
