### ISSUE TITLE
Оформление страницы

### ISSUE THREAD

**Issue by Golenzovskiy** [Golenzovskiy/altrc#4]
Тут по сути две задачи, но поскольку одна маленькая помещаю их в один тикет:
- [x] Альтернативные референции - убрать жирный шрифт и сделать шрифт меньше
- [x] Добавление новой референции (формулировки) – узкая строка, влезает всего 2 последних слова – полностью прочитать текст в режиме правки невозможно

По второму:
![-1](https://cloud.githubusercontent.com/assets/18659104/18265315/ceabf39a-741d-11e6-84e4-df47e8642211.png)
Отцентровать текст референции таким образом, чтобы он начинался где и текст проекта. И поле для ввода текста можно шире

**Comment by Golenzovskiy** [comment]
Первый пункт готов (aa93890f816a8d58fb490c4785b09eaeaf6a02cb, 9552de49418703bae354e59fff2159d851276532).

**Comment by Golenzovskiy** [comment]
Не совсем понятна идея центрирования по тексту проекта. На данный момент реализация требования представляется следующим образом.

![qw1](https://cloud.githubusercontent.com/assets/18659104/18273158/b10d0956-7444-11e6-9d84-2499774ad47b.png)

**Comment by skyeone** [comment]
![b10d0956-7444-11e6-9d84-2499774ad47b](https://cloud.githubusercontent.com/assets/20903401/18276540/fcccb724-7453-11e6-9f64-2feeb3f79566.png)

**Comment by sintsov** [comment]
@skyeone вообще не понятная хрень какая то, сейчас блок референций завис между блоком Компания и Название проекта? Это ошибка или так задумано, кроме того отступ как мне кажется вообще съедает пространство полезное и смысл его не понятен. Возможно мы о разных вещах говорим. Можешь пояснить смысл этого варианта? Кроме того с учетом адаптивности такой отсутп будет смотреться мягко скажем коряво в зависимости от устройства.

**Comment by skyeone** [comment]
Рома, речь идет о центровке поля для ввода текста, саму рамку вы можете двигать как хотите, это не принципиально. Мне этот вариант корявым не кажется, в отличии от ранее предложенных в треде.

Рамка не является активным элементом, только элементом эстетики, она ничего не обслуживает. 

Если вам хочется чтобы все визуально было отцентровано - растяните поле текста на всю ширину страницы или на ширину до буквы "К" в "Компания", а саму рамку на всю ширину. Визуально все будет идеально отцентровано =) Не знаю - зачем, но будет.
