### ISSUE TITLE
Упрощения добавления референций

### ISSUE THREAD

**Issue by sintsov** [Golenzovskiy/altrc#5]
Было высказано мнение заказчика, что сейчас требуется 4 действия. Поэтому возникло предложение сделать например чекбоксы.

**Comment by Golenzovskiy** [comment]
Действительно, сейчас для отбора референций требуется совершить множество действий. Лучшим решением в плане оптимизации действительно будет использование чекбокса. Для придания более привычного понимания этой функциональности (аналогично использованию "избранного" на компьютере) чекбокс может быть стилизован в кнопку-флажок.

Логика может быть следующая: при клике по кнопке "звездочка" референция становится отобранной (добавляется в блок "отобранные"), кнопка меняет свое состояние (цвет). Предлагаю выбрать один из двух вариантов.
![vmaflp-2](https://cloud.githubusercontent.com/assets/18659104/18272928/54947ade-7443-11e6-8db9-9a878141523a.png)
В первом случае отобранные референции подсвечиваются красным, а не отобранные розовым.
Во втором случае отобранные референции подсвечиваются красным, а не отобранные черным.

**Comment by skyeone** [comment]
Второй вариант, но не звездочки, а галки, просто галки =)

Серые - неактивна, красная - выбрана

**Comment by Golenzovskiy** [comment]
Необходимо смержить решение с #7.
@sintsov, я полагаю логичнее решать это мне в рамках #7?

**Comment by sintsov** [comment]
@SGolenzovskiy задача 7 и 5 не связаны, они хоть и касаются референций, но решаются независимо, так что 7 надо просто сделать :)
