### ISSUE TITLE
Как добавлять/убирать в референции описание компании?

### ISSUE THREAD

**Issue by sintsov** [Golenzovskiy/altrc#7]
Любимая тобой задачка на js. Согласно ТЗ у нас было требование, что при нажатие на кнопкочку "добавить описание", оно должно цепляться к тексту референции. Нужно такую опцию сделать (точную формулировку можно глянуть в ТЗ)

По реализации пиши мне в личку.

**Comment by Golenzovskiy** [comment]
ТЗ гласит:

> Если у проекта есть поле описание клиента, то при работе с формулировками должны быть доступна галочка “Добавить описание к формулировкам”, после нажатия на которую все формулировки дополняются описанием. Пример:
> _Анализа рынка газовых компрессоров в России и 6 странах СНГ для компании Howden (глобальный производитель оборудования для обработки воздуха и газа)_
> где в скобках это описание клиента, в противном случае обычно все формулировки заканчиваются названием компании.

**Comment by Golenzovskiy** [comment]
Согласно требованиям к крайнему импорту:

> Обратите внимание, что при заливке проектов, само описание проекта также является его 1м вариантом формулировки. Просто сейчас выходит, что нигде референций нет, а описание проекта - это и есть первая референция

С имеющимися в настоящий момент в БД данными, при отборе референций тех проектов, которые не содержат описания, в отобранные будут попадать значения вида:
_Разработка внутреннего бизнес-плана инжиниринговой компании "ADD Engineering" (ADD Engineering)_

**Comment by skyeone** [comment]
В таких случаях, где текст ничего не поясняет, мы будем редактировать его постепенно, в процессе пользования софтом. Речь и о тексте референции самой и о тексте "описание компании". Так что это не архипроблема.

**Comment by Golenzovskiy** [comment]
Возможно два варианта реализации.
1. Для всех референций добавляется всего одна кнопка "Цеплять описание". При нажатии ну эту кнопку описание цепляется к каждой отбираемой референции проекта.
![image](https://cloud.githubusercontent.com/assets/18659104/18409772/bfb6fc0c-7758-11e6-9def-887891c1a141.png)
2. Кнопка "Цеплять описание" добавляется для каждой референции. При нажатии на эту кнопку описание цепляется только к соответствующей ей референции.
![image](https://cloud.githubusercontent.com/assets/18659104/18409749/5ba37862-7758-11e6-8794-674ddd2995cb.png)

**Comment by sintsov** [comment]
Насколько я помню исходную постановку задачи из ТЗ, нужен просто вариант 1, одна кнопка нажав на нее у тебя прямо в списке референций добавляется в скобках описание, для всех. И потом уже когда ты добавляешь референцию она уже будет снабжена описанием.
