### ISSUE TITLE
Создание preview для изображений

### ISSUE THREAD

**Issue by sintsov** [Golenzovskiy/altrc#8]
Сейчас у нас все изображения отдаются как есть и сжимаются на стороне клиента. Это понятное дело был временный результат.

Нам нужно определить допустимые размеры изображения для листинга проектов и редактирование/добавление проекта. И ресайзить его под нужный размер (создавать превью). При этом оригинал изображения загруженного у нас сохраняется.

**Comment by sintsov** [comment]
http://devartisans.com/articles/resize-images-laravel5.1
https://laracasts.com/discuss/channels/general-discussion/laravel-5-image-upload-and-resize
https://github.com/Intervention/image

в нашем случае все проще, т.к. не нужно делать ресайз при загрузке, я бы делал так:
перед отображением изображения, делал бы первый раз ресайз, после чего при повторном запросе этого изображения, я бы провреял существует ли файлик ресайза если да, берем его, если нет, тогда делаем ресайз.

**Comment by SGolenzovskiy** [comment]
> Все логотипы должны быть 4 см по ширине, 1.8 по высоте. Если не выходит так подогнать, то или/или в зависимости от того, высокий или вытянутый логотип

**Comment by Golenzovskiy** [comment]
**FYI**: после слияния необходимо выполнить:
`composer install`
